OPENAI_API_KEY="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"
D_ID_API_KEY="ZGVzaGFnb3VuaW1hbmFzYUBnbWFpbC5jb20:YJmjtQU1JXqfK89tzMelD"
